### ISSUE TITLE
Plugin won't work on 4.7.1 version

### ISSUE THREAD

**Issue by pchaploutskii** [matomo-org/plugin-EnvironmentVariables#11]
Plugin won't picked up database ENV VAR settings host, username and password
Works with 4.4.1

**Comment by mbrodala** [comment]
Can you retry with newer versions? At least 5.x seems to work fine.

**Comment by snake14** [comment]
Closing this issue as it appears to have been fixed in the latest version. Please feel free to re-open if you are still experiencing the issue.
